categories = [
{'id': 1, 'name': 'motorbike'},
{'id': 2, 'name': 'kitchen counter'},
{'id': 3, 'name': 'shovel'},
{'id': 4, 'name': 'fire sprinkler'},
{'id': 5, 'name': 'paneling'},
{'id': 6, 'name': 'coffee maker'},
{'id': 7, 'name': 'platform'},
{'id': 8, 'name': 'toilet bin'},
{'id': 9, 'name': 'floor trim'},
{'id': 10, 'name': 'towel rack'},
{'id': 11, 'name': 'stair wall'},
{'id': 12, 'name': 'bathroom art'},
{'id': 13, 'name': 'ball'},
{'id': 14, 'name': 'clothes hanger'},
{'id': 15, 'name': 'wine cabinet'},
{'id': 16, 'name': 'stovetop'},
{'id': 17, 'name': 'beanbag chair'},
{'id': 18, 'name': 'piano bench'},
{'id': 19, 'name': 'gap'},
{'id': 20, 'name': 'bush'},
{'id': 21, 'name': 'plant ridge'},
{'id': 22, 'name': 'copier machine'},
{'id': 23, 'name': 'weight bench'},
{'id': 24, 'name': 'door frame'},
{'id': 25, 'name': 'towel bar'},
{'id': 26, 'name': 'doorframe'},
{'id': 27, 'name': 'floor stand'},
{'id': 28, 'name': 'bathroom fan'},
{'id': 29, 'name': 'motion detector'},
{'id': 30, 'name': 'step'},
{'id': 31, 'name': 'bedstead'},
{'id': 32, 'name': 'doormat'},
{'id': 33, 'name': 'banister'},
{'id': 34, 'name': 'kitchen island'},
{'id': 35, 'name': 'art frame'},
{'id': 36, 'name': 'skateboard'},
{'id': 37, 'name': 'teapot'},
{'id': 38, 'name': 'bedside lamp'},
{'id': 39, 'name': 'sink table'},
{'id': 40, 'name': 'projector screen'},
{'id': 41, 'name': 'shirt'},
{'id': 42, 'name': 'backsplash'},
{'id': 43, 'name': 'ventilation hood'},
{'id': 44, 'name': 'computer mouse'},
{'id': 45, 'name': 'ceiling dome'},
{'id': 46, 'name': 'yard'},
{'id': 47, 'name': 'boarder'},
{'id': 48, 'name': 'towel holder'},
{'id': 49, 'name': 'decor'},
{'id': 50, 'name': 'clothes dryer'},
{'id': 51, 'name': 'bar'},
{'id': 52, 'name': 'under stair'},
{'id': 53, 'name': 'energy box'},
{'id': 54, 'name': 'side table'},
{'id': 55, 'name': 'dress'},
{'id': 56, 'name': 'coffee table'},
{'id': 57, 'name': 'workstation'},
{'id': 58, 'name': 'candle'},
{'id': 59, 'name': 'window valence'},
{'id': 60, 'name': 'risers for theater seating'},
{'id': 61, 'name': 'curtain rod'},
{'id': 62, 'name': 'wood'},
{'id': 63, 'name': 'stick'},
{'id': 64, 'name': 'towel basket'},
{'id': 65, 'name': 'floor elevator'},
{'id': 66, 'name': 'tree'},
{'id': 67, 'name': 'couch'},
{'id': 68, 'name': 'stool'},
{'id': 69, 'name': 'makeup'},
{'id': 70, 'name': 'dirt'},
{'id': 71, 'name': 'bottle of soap'},
{'id': 72, 'name': 'soapbox'},
{'id': 73, 'name': 'maraca'},
{'id': 74, 'name': 'exercise ball'},
{'id': 75, 'name': 'footrest'},
{'id': 76, 'name': 'partition'},
{'id': 77, 'name': 'closet ceiling'},
{'id': 78, 'name': 'ridge'},
{'id': 79, 'name': 'riser'},
{'id': 80, 'name': 'exercise equipment'},
{'id': 81, 'name': 'shower curtain bar'},
{'id': 82, 'name': 'bot'},
{'id': 83, 'name': 'flowerpot'},
{'id': 84, 'name': 'cabinet table'},
{'id': 85, 'name': 'shower hose'},
{'id': 86, 'name': 'leg rest'},
{'id': 87, 'name': 'balcony'},
{'id': 88, 'name': 'tissue box stand'},
{'id': 89, 'name': 'kitchen appliance'},
{'id': 90, 'name': 'entry'},
{'id': 91, 'name': 'oven and stove'},
{'id': 92, 'name': 'water dispenser'},
{'id': 93, 'name': 'baseboard'},
{'id': 94, 'name': 'clothes hamper'},
{'id': 95, 'name': 'tool'},
{'id': 96, 'name': 'dice'},
{'id': 97, 'name': 'mini fridge'},
{'id': 98, 'name': 'table cushion'},
{'id': 99, 'name': 'shrubbery'},
{'id': 100, 'name': 'grill'},
{'id': 101, 'name': 'shower grab bar'},
{'id': 102, 'name': 'trellis'},
{'id': 103, 'name': 'dartboard'},
{'id': 104, 'name': 'bathroom'},
{'id': 105, 'name': 'gift'},
{'id': 106, 'name': 'stair frame'},
{'id': 107, 'name': 'soap bottle'},
{'id': 108, 'name': 'basket of towels'},
{'id': 109, 'name': 'behind'},
{'id': 110, 'name': 'coffee mug'},
{'id': 111, 'name': 'bust'},
{'id': 112, 'name': 'sowing machine'},
{'id': 113, 'name': 'oven'},
{'id': 114, 'name': 'rocking horse'},
{'id': 115, 'name': 'smoke detector'},
{'id': 116, 'name': 'wall cabinet'},
{'id': 117, 'name': 'tripod'},
{'id': 118, 'name': 'mount'},
{'id': 119, 'name': 'title'},
{'id': 120, 'name': 'theater screen'},
{'id': 121, 'name': 'misc'},
{'id': 122, 'name': 'soap dish cubby'},
{'id': 123, 'name': 'pile of magazines'},
{'id': 124, 'name': 'kitchen decoration'},
{'id': 125, 'name': 'food'},
{'id': 126, 'name': 'unknown wall'},
{'id': 127, 'name': 'decorative mask'},
{'id': 128, 'name': 'poll'},
{'id': 129, 'name': 'decorative plate'},
{'id': 130, 'name': 'emergency exit'},
{'id': 131, 'name': 'picture car'},
{'id': 132, 'name': 'control'},
{'id': 133, 'name': 'jar'},
{'id': 134, 'name': 'foot stand'},
{'id': 135, 'name': 'shower'},
{'id': 136, 'name': 'water tank'},
{'id': 137, 'name': 'stringer'},
{'id': 138, 'name': 'board'},
{'id': 139, 'name': 'flag'},
{'id': 140, 'name': 'electric box'},
{'id': 141, 'name': 'chair stand'},
{'id': 142, 'name': 'wet bar'},
{'id': 143, 'name': 'cleaning clutter'},
{'id': 144, 'name': 'pipe'},
{'id': 145, 'name': 'bathroom cabinet'},
{'id': 146, 'name': 'row of theater chairs'},
{'id': 147, 'name': 'balustrade'},
{'id': 148, 'name': 'transformer'},
{'id': 149, 'name': 'a-frame sign'},
{'id': 150, 'name': 'bowl'},
{'id': 151, 'name': 'pew'},
{'id': 152, 'name': 'dresser'},
{'id': 153, 'name': 'stage'},
{'id': 154, 'name': 'dome roof'},
{'id': 155, 'name': 'bed'},
{'id': 156, 'name': 'coat hanger'},
{'id': 157, 'name': 'christmas tree'},
{'id': 158, 'name': 'table tray'},
{'id': 159, 'name': 'wall pack'},
{'id': 160, 'name': 'showerhead'},
{'id': 161, 'name': 'concrete block'},
{'id': 162, 'name': 'outlet'},
{'id': 163, 'name': 'hunting trophy'},
{'id': 164, 'name': 'dining table'},
{'id': 165, 'name': 'bean bag chair'},
{'id': 166, 'name': 'cement drum'},
{'id': 167, 'name': 'bathroom glass'},
{'id': 168, 'name': 'tapestry'},
{'id': 169, 'name': 'projector'},
{'id': 170, 'name': 'sink pipe'},
{'id': 171, 'name': 'toolbox'},
{'id': 172, 'name': 'shade'},
{'id': 173, 'name': 'fuse box'},
{'id': 174, 'name': 'whiteboard'},
{'id': 175, 'name': 'reading table'},
{'id': 176, 'name': 'door/window frame'},
{'id': 177, 'name': 'rods/table'},
{'id': 178, 'name': 'trophy'},
{'id': 179, 'name': 'cooker'},
{'id': 180, 'name': 'hanger'},
{'id': 181, 'name': 'ceiling light fixture connection'},
{'id': 182, 'name': 'end table'},
{'id': 183, 'name': 'wall electronics'},
{'id': 184, 'name': 'kitchen extractor'},
{'id': 185, 'name': 'hose outlet'},
{'id': 186, 'name': 'art/man statue'},
{'id': 187, 'name': 'headboard'},
{'id': 188, 'name': 'storage shelving'},
{'id': 189, 'name': 'soap dish'},
{'id': 190, 'name': 'conference table'},
{'id': 191, 'name': 'cosmetic'},
{'id': 192, 'name': 'socket'},
{'id': 193, 'name': 'highchair'},
{'id': 194, 'name': 'ceiling boarder'},
{'id': 195, 'name': 'jug'},
{'id': 196, 'name': 'unknown - hot tub?'},
{'id': 197, 'name': 'kitchen bell'},
{'id': 198, 'name': 'soft chair'},
{'id': 199, 'name': 'bath faucet'},
{'id': 200, 'name': 'appliance'},
{'id': 201, 'name': 'bar soap'},
{'id': 202, 'name': 'doorknob'},
{'id': 203, 'name': 'lamp table'},
{'id': 204, 'name': 'photo'},
{'id': 205, 'name': 'window shutters'},
{'id': 206, 'name': 'plug'},
{'id': 207, 'name': 'heater'},
{'id': 208, 'name': 'dishrag'},
{'id': 209, 'name': 'wall tv'},
{'id': 210, 'name': 'locker'},
{'id': 211, 'name': 'molding'},
{'id': 212, 'name': 'dining chair'},
{'id': 213, 'name': 'nightstand'},
{'id': 214, 'name': 'hot tub'},
{'id': 215, 'name': 'condiment'},
{'id': 216, 'name': 'axe'},
{'id': 217, 'name': 'credenza'},
{'id': 218, 'name': 'folding table'},
{'id': 219, 'name': 'workbench'},
{'id': 220, 'name': 'blinds'},
{'id': 221, 'name': 'lintel'},
{'id': 222, 'name': 'stairs railing'},
{'id': 223, 'name': 'basketball hoop'},
{'id': 224, 'name': 'switch'},
{'id': 225, 'name': 'exercise bike'},
{'id': 226, 'name': 'door hinge'},
{'id': 227, 'name': 'wardrobe'},
{'id': 228, 'name': 'arcade game'},
{'id': 229, 'name': 'box of tissues'},
{'id': 230, 'name': 'barrel'},
{'id': 231, 'name': 'wall table'},
{'id': 232, 'name': 'kitchen ceiling'},
{'id': 233, 'name': 'pelt'},
{'id': 234, 'name': 'dog bed'},
{'id': 235, 'name': 'patio'},
{'id': 236, 'name': 'toilet stall door'},
{'id': 237, 'name': 'knife'},
{'id': 238, 'name': 'chest of drawers'},
{'id': 239, 'name': 'storage box'},
{'id': 240, 'name': 'shower mat'},
{'id': 241, 'name': 'pillow'},
{'id': 242, 'name': 'cushion'},
{'id': 243, 'name': 'fountain'},
{'id': 244, 'name': 'rope'},
{'id': 245, 'name': 'sculpture'},
{'id': 246, 'name': 'handbag'},
{'id': 247, 'name': 'stand'},
{'id': 248, 'name': 'window dormer'},
{'id': 249, 'name': 'circular sofa'},
{'id': 250, 'name': 'stair step'},
{'id': 251, 'name': 'recliner'},
{'id': 252, 'name': 'shower door frame'},
{'id': 253, 'name': 'kitchen counter support'},
{'id': 254, 'name': 'painting'},
{'id': 255, 'name': 'round cushion'},
{'id': 256, 'name': 'bag of sand'},
{'id': 257, 'name': 'buffet'},
{'id': 258, 'name': 'toilet handle'},
{'id': 259, 'name': 'reflection'},
{'id': 260, 'name': 'moose head/sculpture/hunting trophy'},
{'id': 261, 'name': 'closet storage area'},
{'id': 262, 'name': 'staircase trim'},
{'id': 263, 'name': 'alarm'},
{'id': 264, 'name': 'l-shaped sofa'},
{'id': 265, 'name': 'cuboid'},
{'id': 266, 'name': 'knob'},
{'id': 267, 'name': 'amplifier'},
{'id': 268, 'name': 'clothes'},
{'id': 269, 'name': 'baluster'},
{'id': 270, 'name': 'wall'},
{'id': 271, 'name': 'bed runner'},
{'id': 272, 'name': 'bath sink'},
{'id': 273, 'name': 'door tag'},
{'id': 274, 'name': 'shower ceiling'},
{'id': 275, 'name': 'sconce'},
{'id': 276, 'name': 'fireplace utensil'},
{'id': 277, 'name': 'luggage'},
{'id': 278, 'name': 'window shade'},
{'id': 279, 'name': 'can of paint'},
{'id': 280, 'name': 'storage bin'},
{'id': 281, 'name': 'oven vent'},
{'id': 282, 'name': 'telephone'},
{'id': 283, 'name': 'backrest'},
{'id': 284, 'name': 'ironing board'},
{'id': 285, 'name': 'support'},
{'id': 286, 'name': 'speaker'},
{'id': 287, 'name': 'purse'},
{'id': 288, 'name': 'binder'},
{'id': 289, 'name': 'chair'},
{'id': 290, 'name': 'junk'},
{'id': 291, 'name': 'bottle'},
{'id': 292, 'name': 'robe'},
{'id': 293, 'name': 'towels in a basket'},
{'id': 294, 'name': 'bathrobe'},
{'id': 295, 'name': 'light box frame'},
{'id': 296, 'name': 'wheelbarrow'},
{'id': 297, 'name': 'sink'},
{'id': 298, 'name': 'shower seat'},
{'id': 299, 'name': 'bedding'},
{'id': 300, 'name': 'closet door'},
{'id': 301, 'name': 'window seat'},
{'id': 302, 'name': 'beanbag'},
{'id': 303, 'name': 'media console'},
{'id': 304, 'name': 'tabletop box'},
{'id': 305, 'name': 'unicycle'},
{'id': 306, 'name': 'mortar'},
{'id': 307, 'name': 'bath cabinet'},
{'id': 308, 'name': 'vent'},
{'id': 309, 'name': 'pantry'},
{'id': 310, 'name': 'door stand'},
{'id': 311, 'name': 'rolling pin'},
{'id': 312, 'name': 'table stand'},
{'id': 313, 'name': 'awning'},
{'id': 314, 'name': 'projector opening'},
{'id': 315, 'name': 'fan'},
{'id': 316, 'name': 'figure'},
{'id': 317, 'name': 'soffit'},
{'id': 318, 'name': 'aquarium'},
{'id': 319, 'name': 'pc tower'},
{'id': 320, 'name': 'ceiling pipe'},
{'id': 321, 'name': 'ceiling lamp'},
{'id': 322, 'name': 'bidet'},
{'id': 323, 'name': 'drawer'},
{'id': 324, 'name': 'recessed wall'},
{'id': 325, 'name': 'shower rod'},
{'id': 326, 'name': 'toaster'},
{'id': 327, 'name': 'art/clutter'},
{'id': 328, 'name': 'garage door motor'},
{'id': 329, 'name': 'desert plate'},
{'id': 330, 'name': 'soap dispenser'},
{'id': 331, 'name': 'jacuzzi'},
{'id': 332, 'name': 'tabletop trinket'},
{'id': 333, 'name': 'toilet paper dispenser'},
{'id': 334, 'name': 'door'},
{'id': 335, 'name': 'cart'},
{'id': 336, 'name': 'mouse'},
{'id': 337, 'name': 'pool'},
{'id': 338, 'name': 'yoga mat'},
{'id': 339, 'name': 'wash cabinet'},
{'id': 340, 'name': 'record player'},
{'id': 341, 'name': 'kitchen top'},
{'id': 342, 'name': 'pool table'},
{'id': 343, 'name': 'lighting fixture'},
{'id': 344, 'name': 'bathroom counter'},
{'id': 345, 'name': 'decorative quilt'},
{'id': 346, 'name': 'edge'},
{'id': 347, 'name': 'pitcher'},
{'id': 348, 'name': 'toilet bowl brush holder'},
{'id': 349, 'name': 'rug'},
{'id': 350, 'name': 'bed table'},
{'id': 351, 'name': 'chair rail'},
{'id': 352, 'name': 'tiled floor'},
{'id': 353, 'name': 'stairs'},
{'id': 354, 'name': 'swing door'},
{'id': 355, 'name': 'tissue'},
{'id': 356, 'name': 'dressing table'},
{'id': 357, 'name': 'motorcycle'},
{'id': 358, 'name': 'bed comforter'},
{'id': 359, 'name': 'garage door railing'},
{'id': 360, 'name': 'washing powder'},
{'id': 361, 'name': 'cubicle'},
{'id': 362, 'name': 'show pack'},
{'id': 363, 'name': 'kitchen table'},
{'id': 364, 'name': 'access area'},
{'id': 365, 'name': 'footstool'},
{'id': 366, 'name': 'bathroom stall'},
{'id': 367, 'name': 'foliage'},
{'id': 368, 'name': 'seat'},
{'id': 369, 'name': 'bed sheet'},
{'id': 370, 'name': 'exercise machine'},
{'id': 371, 'name': 'base rail'},
{'id': 372, 'name': 'ceiling inset for fan'},
{'id': 373, 'name': 'objects'},
{'id': 374, 'name': 'light'},
{'id': 375, 'name': 'window'},
{'id': 376, 'name': 'water fountain'},
{'id': 377, 'name': 'portrait'},
{'id': 378, 'name': 'hedge'},
{'id': 379, 'name': 'wall board'},
{'id': 380, 'name': 'table'},
{'id': 381, 'name': 'brochure'},
{'id': 382, 'name': 'plush toy'},
{'id': 383, 'name': 'barbecue'},
{'id': 384, 'name': 'fire extinguisher'},
{'id': 385, 'name': 'treadmill'},
{'id': 386, 'name': 'faucet'},
{'id': 387, 'name': 'sign'},
{'id': 388, 'name': 'basket'},
{'id': 389, 'name': 'fireplace brush'},
{'id': 390, 'name': 'ornament'},
{'id': 391, 'name': 'yarn machine'},
{'id': 392, 'name': 'newspaper basket'},
{'id': 393, 'name': 'cosmetics'},
{'id': 394, 'name': 'wall statue'},
{'id': 395, 'name': 'globe'},
{'id': 396, 'name': 'toilet sliding door'},
{'id': 397, 'name': 'unknown/probably shrubbery'},
{'id': 398, 'name': 'sofa seat'},
{'id': 399, 'name': 'globe stand'},
{'id': 400, 'name': 'dinner table'},
{'id': 401, 'name': 'compound wall'},
{'id': 402, 'name': 'knife holder'},
{'id': 403, 'name': 'ceiling wall'},
{'id': 404, 'name': 'shower valve'},
{'id': 405, 'name': 'box'},
{'id': 406, 'name': 'bathroom towel'},
{'id': 407, 'name': 'display'},
{'id': 408, 'name': 'decoration'},
{'id': 409, 'name': 'shower door'},
{'id': 410, 'name': 'vessel sink'},
{'id': 411, 'name': 'photo mount'},
{'id': 412, 'name': 'tile'},
{'id': 413, 'name': 'shower knob'},
{'id': 414, 'name': 'piano'},
{'id': 415, 'name': 'toilet paper holder'},
{'id': 416, 'name': 'urn'},
{'id': 417, 'name': 'mirror'},
{'id': 418, 'name': 'hook'},
{'id': 419, 'name': 'doorstep'},
{'id': 420, 'name': 'stacked chair'},
{'id': 421, 'name': 'kitchen handle'},
{'id': 422, 'name': 'towel shelf'},
{'id': 423, 'name': 'table lamp'},
{'id': 424, 'name': 'curtain'},
{'id': 425, 'name': 'stair stepper'},
{'id': 426, 'name': 'canvas stand'},
{'id': 427, 'name': 'gate'},
{'id': 428, 'name': 'bottles of wine'},
{'id': 429, 'name': 'boiler'},
{'id': 430, 'name': 'wall cubby'},
{'id': 431, 'name': 'pathway'},
{'id': 432, 'name': 'clothes hanger rod'},
{'id': 433, 'name': 'hanging clothes'},
{'id': 434, 'name': 'stonework'},
{'id': 435, 'name': 'jewelry box'},
{'id': 436, 'name': 'rafter'},
{'id': 437, 'name': 'handle'},
{'id': 438, 'name': 'grandfather clock'},
{'id': 439, 'name': 'storage cabinet'},
{'id': 440, 'name': 'candle holder'},
{'id': 441, 'name': 'wall hanging decoration'},
{'id': 442, 'name': 'rocking chair'},
{'id': 443, 'name': 'row of theater seats'},
{'id': 444, 'name': 'wall indent'},
{'id': 445, 'name': 'weight'},
{'id': 446, 'name': 'tv'},
{'id': 447, 'name': 'toilet seat liner dispenser'},
{'id': 448, 'name': 'carpet roll'},
{'id': 449, 'name': 'round footstool'},
{'id': 450, 'name': 'workout bike'},
{'id': 451, 'name': 'art/muscle shell'},
{'id': 452, 'name': 'scroll'},
{'id': 453, 'name': 'scarf'},
{'id': 454, 'name': 'tv stand'},
{'id': 455, 'name': 'chest drawer'},
{'id': 456, 'name': 'gym equipment'},
{'id': 457, 'name': 'scale'},
{'id': 458, 'name': 'base'},
{'id': 459, 'name': 'bar chair'},
{'id': 460, 'name': 'cutting board'},
{'id': 461, 'name': 'whine shelf'},
{'id': 462, 'name': 'canopy'},
{'id': 463, 'name': 'bread'},
{'id': 464, 'name': 'pedestal'},
{'id': 465, 'name': 'air duct'},
{'id': 466, 'name': 'partial'},
{'id': 467, 'name': 'fire dish'},
{'id': 468, 'name': 'wall stand'},
{'id': 469, 'name': 'closet door knob'},
{'id': 470, 'name': 'exhaust pipe'},
{'id': 471, 'name': 'bell'},
{'id': 472, 'name': 'pillar'},
{'id': 473, 'name': 'sauna bowl'},
{'id': 474, 'name': 'toilet'},
{'id': 475, 'name': 'object /otherroom'},
{'id': 476, 'name': 'ceiling duct'},
{'id': 477, 'name': 'trashcan'},
{'id': 478, 'name': 'closet shelf'},
{'id': 479, 'name': 'hand soap'},
{'id': 480, 'name': 'parapet'},
{'id': 481, 'name': 'attic door'},
{'id': 482, 'name': 'star'},
{'id': 483, 'name': 'candelabra'},
{'id': 484, 'name': 'stall door'},
{'id': 485, 'name': 'book rack'},
{'id': 486, 'name': 'closet floor'},
{'id': 487, 'name': 'dish cabinet'},
{'id': 488, 'name': 'channel'},
{'id': 489, 'name': 'clutter'},
{'id': 490, 'name': 'plumbing'},
{'id': 491, 'name': 'archway corner'},
{'id': 492, 'name': 'kitchen lower cabinet'},
{'id': 493, 'name': 'canvas'},
{'id': 494, 'name': 'table vase'},
{'id': 495, 'name': 'washing machine'},
{'id': 496, 'name': 'clothes container'},
{'id': 497, 'name': 'wall control'},
{'id': 498, 'name': 'top'},
{'id': 499, 'name': 'window closet door'},
{'id': 500, 'name': 'window frame and shelves'},
{'id': 501, 'name': 'bouquet'},
{'id': 502, 'name': 'shower wall cubby'},
{'id': 503, 'name': 'chandelier'},
{'id': 504, 'name': 'kitchen utensil'},
{'id': 505, 'name': 'antique telephone'},
{'id': 506, 'name': 'rack'},
{'id': 507, 'name': 'paper'},
{'id': 508, 'name': 'stack'},
{'id': 509, 'name': 'table vase soil'},
{'id': 510, 'name': 'mirror frame'},
{'id': 511, 'name': 'semi chair'},
{'id': 512, 'name': 'sitting area'},
{'id': 513, 'name': 'elevator'},
{'id': 514, 'name': 'stone bench'},
{'id': 515, 'name': 'apron'},
{'id': 516, 'name': 'fireplace'},
{'id': 517, 'name': 'table light'},
{'id': 518, 'name': 'electrical controller'},
{'id': 519, 'name': 'air conditioner'},
{'id': 520, 'name': 'shower handle'},
{'id': 521, 'name': 'stationery'},
{'id': 522, 'name': 'ceiling vent'},
{'id': 523, 'name': 'garage door'},
{'id': 524, 'name': 'column statue'},
{'id': 525, 'name': 'sauna heater'},
{'id': 526, 'name': 'washing stuff'},
{'id': 527, 'name': 'archway'},
{'id': 528, 'name': 'extractor fan'},
{'id': 529, 'name': 'handrail'},
{'id': 530, 'name': 'bath towel'},
{'id': 531, 'name': 'shoe'},
{'id': 532, 'name': 'pole'},
{'id': 533, 'name': 'garage light'},
{'id': 534, 'name': 'cover'},
{'id': 535, 'name': 'closet rod'},
{'id': 536, 'name': 'shower rail'},
{'id': 537, 'name': 'drum'},
{'id': 538, 'name': 'flowerbed'},
{'id': 539, 'name': 'roof'},
{'id': 540, 'name': 'bedframe'},
{'id': 541, 'name': 'toaster oven'},
{'id': 542, 'name': 'fluorescent light'},
{'id': 543, 'name': 'drill'},
{'id': 544, 'name': 'toilet cleaner'},
{'id': 545, 'name': 'computer'},
{'id': 546, 'name': 'plant'},
{'id': 547, 'name': 'recycle bin'},
{'id': 548, 'name': 'water heater'},
{'id': 549, 'name': 'dirt ground'},
{'id': 550, 'name': 'tissue box'},
{'id': 551, 'name': 'massage bed'},
{'id': 552, 'name': 'frame for door'},
{'id': 553, 'name': 'soap'},
{'id': 554, 'name': 'shower curtain rod'},
{'id': 555, 'name': 'tablet computer'},
{'id': 556, 'name': 'cooker unit'},
{'id': 557, 'name': 'landing'},
{'id': 558, 'name': 'paper towel dispenser'},
{'id': 559, 'name': 'tank'},
{'id': 560, 'name': 'plant soil'},
{'id': 561, 'name': 'watch'},
{'id': 562, 'name': 'clothing stand'},
{'id': 563, 'name': 'folding stand'},
{'id': 564, 'name': 'panel screen'},
{'id': 565, 'name': 'barbers chair'},
{'id': 566, 'name': 'office table'},
{'id': 567, 'name': 'hearst'},
{'id': 568, 'name': 'ceiling under stairs'},
{'id': 569, 'name': 'spice rack'},
{'id': 570, 'name': 'throw blanket'},
{'id': 571, 'name': 'ventilation'},
{'id': 572, 'name': 'show space'},
{'id': 573, 'name': 'refrigerator cabinet'},
{'id': 574, 'name': 'pip'},
{'id': 575, 'name': 'vending machine'},
{'id': 576, 'name': 'frame'},
{'id': 577, 'name': 'garage door opener motor'},
{'id': 578, 'name': 'stairs skirt'},
{'id': 579, 'name': 'garage door opener'},
{'id': 580, 'name': 'wall beam'},
{'id': 581, 'name': 'dining bench'},
{'id': 582, 'name': 'pot'},
{'id': 583, 'name': 'statue'},
{'id': 584, 'name': 'folding chair'},
{'id': 585, 'name': 'freezer'},
{'id': 586, 'name': 'closest area'},
{'id': 587, 'name': 'laundry bag'},
{'id': 588, 'name': 'button'},
{'id': 589, 'name': 'watering can'},
{'id': 590, 'name': 'desk chair'},
{'id': 591, 'name': 'lounge chair'},
{'id': 592, 'name': 'cardboard box'},
{'id': 593, 'name': 'theater stage'},
{'id': 594, 'name': 'beam across top of arch'},
{'id': 595, 'name': 'stone'},
{'id': 596, 'name': 'unknown clutter'},
{'id': 597, 'name': 'ceiling under staircase'},
{'id': 598, 'name': 'kitchen wall'},
{'id': 599, 'name': 'stair handle'},
{'id': 600, 'name': 'column'},
{'id': 601, 'name': 'three'},
{'id': 602, 'name': 'closet area for hanging clothes'},
{'id': 603, 'name': 'antique clock'},
{'id': 604, 'name': 'wine rack'},
{'id': 605, 'name': 'clock'},
{'id': 606, 'name': 'altar'},
{'id': 607, 'name': 'garage door frame'},
{'id': 608, 'name': 'ceiling bedroom'},
{'id': 609, 'name': 'mixer'},
{'id': 610, 'name': 'security camera'},
{'id': 611, 'name': 'pan'},
{'id': 612, 'name': 'kitchen countertop items'},
{'id': 613, 'name': 'tabletop'},
{'id': 614, 'name': 'box of fruit'},
{'id': 615, 'name': 'mat'},
{'id': 616, 'name': 'perfume'},
{'id': 617, 'name': 'kitchen shelf'},
{'id': 618, 'name': 'table clutter'},
{'id': 619, 'name': 'screen'},
{'id': 620, 'name': 'island'},
{'id': 621, 'name': 'chimney'},
{'id': 622, 'name': 'shower bar'},
{'id': 623, 'name': 'utensil'},
{'id': 624, 'name': 'artwork'},
{'id': 625, 'name': 'toy duck'},
{'id': 626, 'name': 'desk'},
{'id': 627, 'name': 'swimming pool'},
{'id': 628, 'name': 'drawer desk'},
{'id': 629, 'name': 'ceiling fixture'},
{'id': 630, 'name': 'plant ornament'},
{'id': 631, 'name': 'kettle'},
{'id': 632, 'name': 'bonsai tree'},
{'id': 633, 'name': 'toy giraffe'},
{'id': 634, 'name': 'shower floor'},
{'id': 635, 'name': 'bedpost'},
{'id': 636, 'name': 'wine bottle'},
{'id': 637, 'name': 'grass'},
{'id': 638, 'name': 'french door'},
{'id': 639, 'name': 'iron board'},
{'id': 640, 'name': 'floor mat'},
{'id': 641, 'name': 'light fixture'},
{'id': 642, 'name': 'window screen'},
{'id': 643, 'name': 'broom'},
{'id': 644, 'name': 'wall desk'},
{'id': 645, 'name': 'countertop'},
{'id': 646, 'name': 'computer desk'},
{'id': 647, 'name': 'liquid soap'},
{'id': 648, 'name': 'water pump'},
{'id': 649, 'name': 'roomba'},
{'id': 650, 'name': 'trash bag'},
{'id': 651, 'name': 'decorative plant'},
{'id': 652, 'name': 'unknown'},
{'id': 653, 'name': 'window glass'},
{'id': 654, 'name': 'container'},
{'id': 655, 'name': 'bathtub platform'},
{'id': 656, 'name': 'fruit'},
{'id': 657, 'name': 'fire alarm'},
{'id': 658, 'name': 'slab'},
{'id': 659, 'name': 'stove door'},
{'id': 660, 'name': 'unknown stove accessory'},
{'id': 661, 'name': 'coffee machine'},
{'id': 662, 'name': 'air conditioning'},
{'id': 663, 'name': 'bed small'},
{'id': 664, 'name': 'washer-dryer'},
{'id': 665, 'name': 'unknown kitchen appliance'},
{'id': 666, 'name': 'fireplace sconce'},
{'id': 667, 'name': 'foosball table'},
{'id': 668, 'name': 'dog'},
{'id': 669, 'name': 'tree branch'},
{'id': 670, 'name': 'decorative bowl'},
{'id': 671, 'name': 'closet'},
{'id': 672, 'name': 'object'},
{'id': 673, 'name': 'cabinet door'},
{'id': 674, 'name': 'cabinet counter'},
{'id': 675, 'name': 'food stand'},
{'id': 676, 'name': 'rack of weights'},
{'id': 677, 'name': 'diploma'},
{'id': 678, 'name': 'ceiling molding'},
{'id': 679, 'name': 'bedroom ceiling'},
{'id': 680, 'name': 'rod'},
{'id': 681, 'name': 'chaise'},
{'id': 682, 'name': 'wall of statue inset'},
{'id': 683, 'name': 'wall soap shelf'},
{'id': 684, 'name': 'urinal'},
{'id': 685, 'name': 'fume cupboard'},
{'id': 686, 'name': 'belt'},
{'id': 687, 'name': 'ledge'},
{'id': 688, 'name': 'roof grill'},
{'id': 689, 'name': 'round chair'},
{'id': 690, 'name': 'easy chair'},
{'id': 691, 'name': 'bulletin board'},
{'id': 692, 'name': 'wall clock'},
{'id': 693, 'name': 'platter'},
{'id': 694, 'name': 'bed stand'},
{'id': 695, 'name': 'trinket'},
{'id': 696, 'name': 'supporting structure'},
{'id': 697, 'name': 'tissue paper'},
{'id': 698, 'name': 'electric outlet'},
{'id': 699, 'name': 'sliding door'},
{'id': 700, 'name': 'plate of food'},
{'id': 701, 'name': 'dining table centerpiece'},
{'id': 702, 'name': 'printer'},
{'id': 703, 'name': 'stairwell'},
{'id': 704, 'name': 'crib'},
{'id': 705, 'name': 'overhang'},
{'id': 706, 'name': 'shower case'},
{'id': 707, 'name': 'ashtray'},
{'id': 708, 'name': 'camera'},
{'id': 709, 'name': 'hand wash'},
{'id': 710, 'name': 'briefcase'},
{'id': 711, 'name': 'bowl of fruit'},
{'id': 712, 'name': 'rotunda railing'},
{'id': 713, 'name': 'rock'},
{'id': 714, 'name': 'stove'},
{'id': 715, 'name': 'teddy bear'},
{'id': 716, 'name': 'fireplace wall'},
{'id': 717, 'name': 'safe'},
{'id': 718, 'name': 'fruit dish'},
{'id': 719, 'name': 'power breaker box'},
{'id': 720, 'name': 'sofa chair'},
{'id': 721, 'name': 'dinnerware'},
{'id': 722, 'name': 'swing'},
{'id': 723, 'name': 'door window'},
{'id': 724, 'name': 'floor lamp'},
{'id': 725, 'name': 'painting frame'},
{'id': 726, 'name': 'shower wall'},
{'id': 727, 'name': 'bookshelf'},
{'id': 728, 'name': 'railing'},
{'id': 729, 'name': 'shower stall'},
{'id': 730, 'name': 'storage'},
{'id': 731, 'name': 'door handle'},
{'id': 732, 'name': 'armchair'},
{'id': 733, 'name': 'bin'},
{'id': 734, 'name': 'hole'},
{'id': 735, 'name': 'sauna heat rocks'},
{'id': 736, 'name': 'desk lamp'},
{'id': 737, 'name': 'exercise mat'},
{'id': 738, 'name': 'display case'},
{'id': 739, 'name': 'bathroom shelf'},
{'id': 740, 'name': 'electric wire casing'},
{'id': 741, 'name': 'barricade'},
{'id': 742, 'name': 'vanity'},
{'id': 743, 'name': 'garage door opener bar'},
{'id': 744, 'name': 'unknown picture/window'},
{'id': 745, 'name': 'shower caddy'},
{'id': 746, 'name': 'shelves /otherroom'},
{'id': 747, 'name': 'rail'},
{'id': 748, 'name': 'ladder'},
{'id': 749, 'name': 'shelving'},
{'id': 750, 'name': 'mantle'},
{'id': 751, 'name': 'table plant'},
{'id': 752, 'name': 'bar cabinet'},
{'id': 753, 'name': 'shower-bath cabinet'},
{'id': 754, 'name': 'sofa set'},
{'id': 755, 'name': 'fire screen'},
{'id': 756, 'name': 'bottom of stairs'},
{'id': 757, 'name': 'shower curtain'},
{'id': 758, 'name': 'washbasin counter'},
{'id': 759, 'name': 'patio floor'},
{'id': 760, 'name': 'picture'},
{'id': 761, 'name': 'tablet'},
{'id': 762, 'name': 'thermostat'},
{'id': 763, 'name': 'picure'},
{'id': 764, 'name': 'picture frame'},
{'id': 765, 'name': 'casket'},
{'id': 766, 'name': 'chicken'},
{'id': 767, 'name': 'exercise mat roll'},
{'id': 768, 'name': 'shower tub'},
{'id': 769, 'name': 'spa bench'},
{'id': 770, 'name': 'alarm control'},
{'id': 771, 'name': 'small table/stand'},
{'id': 772, 'name': 'round seat'},
{'id': 773, 'name': 'chest'},
{'id': 774, 'name': 'dome'},
{'id': 775, 'name': 'sideboard'},
{'id': 776, 'name': 'towel box'},
{'id': 777, 'name': 'lookout'},
{'id': 778, 'name': 'window shutter'},
{'id': 779, 'name': 'entertainment set'},
{'id': 780, 'name': 'counter'},
{'id': 781, 'name': 'window curtain'},
{'id': 782, 'name': 'shower glass /shifted'},
{'id': 783, 'name': 'coat rack'},
{'id': 784, 'name': 'planter curb'},
{'id': 785, 'name': 'refrigerator'},
{'id': 786, 'name': 'beside table'},
{'id': 787, 'name': 'vessel'},
{'id': 788, 'name': 'clothes rack'},
{'id': 789, 'name': 'snow globe'},
{'id': 790, 'name': 'furniture'},
{'id': 791, 'name': 'plate'},
{'id': 792, 'name': 'folder'},
{'id': 793, 'name': 'cloth'},
{'id': 794, 'name': 'ceiling lower'},
{'id': 795, 'name': 'laundry basket'},
{'id': 796, 'name': 'softer'},
{'id': 797, 'name': 'floor'},
{'id': 798, 'name': 'hat'},
{'id': 799, 'name': 'holy cross'},
{'id': 800, 'name': 'desk clutter'},
{'id': 801, 'name': 'lid'},
{'id': 802, 'name': 'file cabinet'},
{'id': 803, 'name': 'washing machine and dryer'},
{'id': 804, 'name': 'curtain lighter'},
{'id': 805, 'name': 'pouffe'},
{'id': 806, 'name': 'recessed cubby'},
{'id': 807, 'name': 'ottoman'},
{'id': 808, 'name': 'tap'},
{'id': 809, 'name': 'monitor'},
{'id': 810, 'name': 'shelf'},
{'id': 811, 'name': 'elliptical'},
{'id': 812, 'name': 'cup'},
{'id': 813, 'name': 'rocky ground'},
{'id': 814, 'name': 'sheet'},
{'id': 815, 'name': 'machine'},
{'id': 816, 'name': 'set of armchairs'},
{'id': 817, 'name': 'keyboard piano'},
{'id': 818, 'name': 'doorway'},
{'id': 819, 'name': 'laptop'},
{'id': 820, 'name': 'water cooler'},
{'id': 821, 'name': 'umbrella'},
{'id': 822, 'name': 'wall toilet paper'},
{'id': 823, 'name': 'display table'},
{'id': 824, 'name': 'piano stool'},
{'id': 825, 'name': 'bathtub utensil'},
{'id': 826, 'name': 'typewriter'},
{'id': 827, 'name': 'doll'},
{'id': 828, 'name': 'wall detail'},
{'id': 829, 'name': 'door stopper'},
{'id': 830, 'name': 'rolling cart'},
{'id': 831, 'name': 'ceiling fan'},
{'id': 832, 'name': 'flower vase'},
{'id': 833, 'name': 'valance'},
{'id': 834, 'name': 'curtain rail'},
{'id': 835, 'name': 'bathroom accessory'},
{'id': 836, 'name': 'grate'},
{'id': 837, 'name': 'trash bin'},
{'id': 838, 'name': 'laundry machine'},
{'id': 839, 'name': 'worktop'},
{'id': 840, 'name': 'boxes /w books'},
{'id': 841, 'name': 'firewood'},
{'id': 842, 'name': 'brush'},
{'id': 843, 'name': 'kitchen cabinet'},
{'id': 844, 'name': 'mantel'},
{'id': 845, 'name': 'ceiling corridor'},
{'id': 846, 'name': 'massage table'},
{'id': 847, 'name': 'drawer sink table'},
{'id': 848, 'name': 'laundry'},
{'id': 849, 'name': 'toilet brush holder'},
{'id': 850, 'name': 'calendar'},
{'id': 851, 'name': 'lights/deco'},
{'id': 852, 'name': 'closet mirror wall'},
{'id': 853, 'name': 'vase'},
{'id': 854, 'name': 'ceiling bath'},
{'id': 855, 'name': 'hand cloth'},
{'id': 856, 'name': 'car battery'},
{'id': 857, 'name': 'coat'},
{'id': 858, 'name': 'computer tower'},
{'id': 859, 'name': 'unknown kitchen stuff'},
{'id': 860, 'name': 'gable'},
{'id': 861, 'name': 'elephant sculpture'},
{'id': 862, 'name': 'throne'},
{'id': 863, 'name': 'computer equipment'},
{'id': 864, 'name': 'shower glass'},
{'id': 865, 'name': 'toilet stall'},
{'id': 866, 'name': 'hoses for chemical tank'},
{'id': 867, 'name': 'alarm clock'},
{'id': 868, 'name': 'glass'},
{'id': 869, 'name': 'smoke alarm'},
{'id': 870, 'name': 'skylight'},
{'id': 871, 'name': 'sliding glass door'},
{'id': 872, 'name': 'shrine'},
{'id': 873, 'name': 'ceiling window'},
{'id': 874, 'name': 'columned perimeter'},
{'id': 875, 'name': 'beam'},
{'id': 876, 'name': 'fence'},
{'id': 877, 'name': 'exit sign'},
{'id': 878, 'name': 'towel bar shelf'},
{'id': 879, 'name': 'carpet'},
{'id': 880, 'name': 'ping pong table'},
{'id': 881, 'name': 'toilet brush'},
{'id': 882, 'name': 'draw'},
{'id': 883, 'name': 'ceiling door'},
{'id': 884, 'name': 'unknown - probably part of trellis -- maybe blinds'},
{'id': 885, 'name': 'hose'},
{'id': 886, 'name': 'book display'},
{'id': 887, 'name': 'baby changing station'},
{'id': 888, 'name': 'pulpit'},
{'id': 889, 'name': 'bag'},
{'id': 890, 'name': 'tarp'},
{'id': 891, 'name': 'keyboard'},
{'id': 892, 'name': 'candlestick'},
{'id': 893, 'name': 'hutch'},
{'id': 894, 'name': 'lion'},
{'id': 895, 'name': 'jacket'},
{'id': 896, 'name': 'scaffolding'},
{'id': 897, 'name': 'basin'},
{'id': 898, 'name': 'billow'},
{'id': 899, 'name': 'dustpan'},
{'id': 900, 'name': 'tablecloth'},
{'id': 901, 'name': 'terrace door'},
{'id': 902, 'name': 'storage space'},
{'id': 903, 'name': 'stone support structure'},
{'id': 904, 'name': 'person'},
{'id': 905, 'name': 'makeup area'},
{'id': 906, 'name': 'stuffed animal'},
{'id': 907, 'name': 'rotunda wall'},
{'id': 908, 'name': 'night table'},
{'id': 909, 'name': 'bicycle'},
{'id': 910, 'name': 'fruit bowl'},
{'id': 911, 'name': 'window frame'},
{'id': 912, 'name': 'ceiling'},
{'id': 913, 'name': 'place mat'},
{'id': 914, 'name': 'curtain valence'},
{'id': 915, 'name': 'magazine'},
{'id': 916, 'name': 'fencing'},
{'id': 917, 'name': 'shower bench'},
{'id': 918, 'name': 'wall sign'},
{'id': 919, 'name': 'art/statue'},
{'id': 920, 'name': 'self side'},
{'id': 921, 'name': 'fireplace tool set'},
{'id': 922, 'name': 'flower stand'},
{'id': 923, 'name': 'cross'},
{'id': 924, 'name': 'copier'},
{'id': 925, 'name': 'yellow egg shaped vase'},
{'id': 926, 'name': 'panel'},
{'id': 927, 'name': 'lamp stand'},
{'id': 928, 'name': 'bed light'},
{'id': 929, 'name': 'soap dispenser shelf in shower'},
{'id': 930, 'name': 'furnace'},
{'id': 931, 'name': 'shelf cubby'},
{'id': 932, 'name': 'bottle of detergent'},
{'id': 933, 'name': 'mirror door'},
{'id': 934, 'name': 'chair part'},
{'id': 935, 'name': 'hall top'},
{'id': 936, 'name': 'wine'},
{'id': 937, 'name': 'heat'},
{'id': 938, 'name': 'domino decoration'},
{'id': 939, 'name': 'falling light'},
{'id': 940, 'name': 'sink cabinet'},
{'id': 941, 'name': 'portal'},
{'id': 942, 'name': 'wreath'},
{'id': 943, 'name': 'window reflection'},
{'id': 944, 'name': 'office chair'},
{'id': 945, 'name': 'towel'},
{'id': 946, 'name': 'doorpost'},
{'id': 947, 'name': 'playpen'},
{'id': 948, 'name': 'john'},
{'id': 949, 'name': 'book'},
{'id': 950, 'name': 'range hood'},
{'id': 951, 'name': 'pool stick'},
{'id': 952, 'name': 'towel ring'},
{'id': 953, 'name': 'tray'},
{'id': 954, 'name': 'display cabinet'},
{'id': 955, 'name': 'sewing machine'},
{'id': 956, 'name': 'stone circle'},
{'id': 957, 'name': 'air vent'},
{'id': 958, 'name': 'drinking fountain'},
{'id': 959, 'name': 'backpack'},
{'id': 960, 'name': 'telescope'},
{'id': 961, 'name': 'stack of papers'},
{'id': 962, 'name': 'stall'},
{'id': 963, 'name': 'food tray'},
{'id': 964, 'name': 'vacuum cleaner'},
{'id': 965, 'name': 'giraffe'},
{'id': 966, 'name': 'art stand'},
{'id': 967, 'name': 'wall lamp'},
{'id': 968, 'name': 'fixture'},
{'id': 969, 'name': 'blackboard'},
{'id': 970, 'name': 'pad'},
{'id': 971, 'name': 'curb'},
{'id': 972, 'name': 'closet shelving'},
{'id': 973, 'name': 'blanket'},
{'id': 974, 'name': 'cabin'},
{'id': 975, 'name': 'bath utensil'},
{'id': 976, 'name': 'extractor'},
{'id': 977, 'name': 'clothes bag'},
{'id': 978, 'name': 'dustbin'},
{'id': 979, 'name': 'shampoo'},
{'id': 980, 'name': 'cuddly toy'},
{'id': 981, 'name': 'computer chair'},
{'id': 982, 'name': 'support beam'},
{'id': 983, 'name': 'canister'},
{'id': 984, 'name': 'dishwasher'},
{'id': 985, 'name': 'separator'},
{'id': 986, 'name': 'table support'},
{'id': 987, 'name': 'dumbbell'},
{'id': 988, 'name': 'spiderman statue'},
{'id': 989, 'name': 'shower dial'},
{'id': 990, 'name': 'post'},
{'id': 991, 'name': 'door knob'},
{'id': 992, 'name': 'counter door'},
{'id': 993, 'name': 'wall panel'},
{'id': 994, 'name': 'patio chair'},
{'id': 995, 'name': 'newspaper'},
{'id': 996, 'name': 'painting /otherroom'},
{'id': 997, 'name': 'step stool'},
{'id': 998, 'name': 'shower pipe'},
{'id': 999, 'name': 'control panel'},
{'id': 1000, 'name': 'toy'},
{'id': 1001, 'name': 'icebox'},
{'id': 1002, 'name': 'toiletry'},
{'id': 1003, 'name': 'tanning bed'},
{'id': 1004, 'name': 'swivel chair'},
{'id': 1005, 'name': 'bench'},
{'id': 1006, 'name': 'medicine cabinet'},
{'id': 1007, 'name': 'skirting'},
{'id': 1008, 'name': 'rotunda'},
{'id': 1009, 'name': 'high shelf'},
{'id': 1010, 'name': 'chunk of art'},
{'id': 1011, 'name': 'duct'},
{'id': 1012, 'name': 'shower soap shelf'},
{'id': 1013, 'name': 'drawers for clothes'},
{'id': 1014, 'name': 'toilet plunger'},
{'id': 1015, 'name': 'sensor'},
{'id': 1016, 'name': 'bed curtain'},
{'id': 1017, 'name': 'easel'},
{'id': 1018, 'name': 'bath wall'},
{'id': 1019, 'name': 'arch'},
{'id': 1020, 'name': 'framing'},
{'id': 1021, 'name': 'staircase'},
{'id': 1022, 'name': 'bathtub'},
{'id': 1023, 'name': 'lampshade'},
{'id': 1024, 'name': 'skirting board'},
{'id': 1025, 'name': 'firewood holder'},
{'id': 1026, 'name': 'bathroom window'},
{'id': 1027, 'name': 'shower tap'},
{'id': 1028, 'name': 'bath mat'},
{'id': 1029, 'name': 'radio'},
{'id': 1030, 'name': 'paper storage'},
{'id': 1031, 'name': 'entrance'},
{'id': 1032, 'name': 'electrical box'},
{'id': 1033, 'name': 'case'},
{'id': 1034, 'name': 'light switch'},
{'id': 1035, 'name': 'hearth'},
{'id': 1036, 'name': 'hot water/cold water knob'},
{'id': 1037, 'name': 'wall top'},
{'id': 1038, 'name': 'washbasin'},
{'id': 1039, 'name': 'lamp'},
{'id': 1040, 'name': 'bathroom utensil'},
{'id': 1041, 'name': 'radiator'},
{'id': 1042, 'name': 'car'},
{'id': 1043, 'name': 'chemical tank'},
{'id': 1044, 'name': 'fish picture'},
{'id': 1045, 'name': 'comforter'},
{'id': 1046, 'name': 'fireplace mirror'},
{'id': 1047, 'name': 'basket of something'},
{'id': 1048, 'name': 'light box'},
{'id': 1049, 'name': 'wall post'},
{'id': 1050, 'name': 'door locker handle'},
{'id': 1051, 'name': 'door bottom rail'},
{'id': 1052, 'name': 'box opening'},
{'id': 1053, 'name': 'toilet sink'},
{'id': 1054, 'name': 'bucket'},
{'id': 1055, 'name': 'desk and chairs'},
{'id': 1056, 'name': 'staircase handrail'},
{'id': 1057, 'name': 'bath deco'},
{'id': 1058, 'name': 'shower cabin'},
{'id': 1059, 'name': 'washcloth'},
{'id': 1060, 'name': 'fuse panel'},
{'id': 1061, 'name': 'microwave'},
{'id': 1062, 'name': 'bureau'},
{'id': 1063, 'name': 'towel rod'},
{'id': 1064, 'name': 'paper towel'},
{'id': 1065, 'name': 'heater piping'},
{'id': 1066, 'name': 'remove'},
{'id': 1067, 'name': 'steps wall'},
{'id': 1068, 'name': 'kitchen countertop item'},
{'id': 1069, 'name': 'box of tissue'},
{'id': 1070, 'name': 'water basin'},
{'id': 1071, 'name': 'cabinet'},
{'id': 1072, 'name': 'fire pit'},
{'id': 1073, 'name': 'led tv'},
{'id': 1074, 'name': 'can'},
{'id': 1075, 'name': 'hammock'},
{'id': 1076, 'name': 'podium'},
{'id': 1077, 'name': 'foosball game table'},
{'id': 1078, 'name': 'toilet paper'},
{'id': 1079, 'name': 'stair'},
{'id': 1080, 'name': 'balcony railing'},
{'id': 1081, 'name': 'wall showcase'},
{'id': 1082, 'name': 'guitar'},
{'id': 1083, 'name': 'oil lamp'},
{'id': 1084, 'name': 'fish tank'},
]