categories = [
{'id': 1, 'name': 'bed'},
{'id': 2, 'name': 'sofa'},
{'id': 3, 'name': 'chair'},
{'id': 4, 'name': 'television set'},
{'id': 5, 'name': 'potted plant'},
{'id': 6, 'name': 'toilet'},
{'id': 7, 'name': 'lamp'},
{'id': 8, 'name': 'desk'},
{'id': 9, 'name': 'bookshelf'},
{'id': 10, 'name': 'cupboard'},
{'id': 11, 'name': 'drawer'},
{'id': 12, 'name': 'refrigerator'},
{'id': 13, 'name': 'oven'},
{'id': 14, 'name': 'microwave'},
{'id': 15, 'name': 'toaster'},
{'id': 16, 'name': 'sink'},
{'id': 17, 'name': 'dishwasher'},
{'id': 18, 'name': 'coffee machine'},
{'id': 19, 'name': 'kettle'},
{'id': 20, 'name': 'stove'},
{'id': 21, 'name': 'washing machine'},
{'id': 22, 'name': 'dryer'},
{'id': 23, 'name': 'mirror'},
{'id': 24, 'name': 'clock'},
{'id': 25, 'name': 'curtains'},
{'id': 26, 'name': 'blinds'},
{'id': 27, 'name': 'bathtub'},
{'id': 28, 'name': 'shower'},
{'id': 29, 'name': 'table'},
{'id': 30, 'name': 'towel'},
{'id': 31, 'name': 'soap dispenser'},
{'id': 32, 'name': 'toothbrush'},
{'id': 33, 'name': 'toothpaste'},
{'id': 34, 'name': 'shampoo'},
{'id': 35, 'name': 'conditioner'},
{'id': 36, 'name': 'hair dryer'},
{'id': 37, 'name': 'razor'},
{'id': 38, 'name': 'makeup'},
{'id': 39, 'name': 'tissue box'},
{'id': 40, 'name': 'trash can'},
{'id': 41, 'name': 'vacuum cleaner'},
{'id': 42, 'name': 'mop'},
{'id': 43, 'name': 'broom'},
{'id': 44, 'name': 'bucket'},
{'id': 45, 'name': 'sponge'},
{'id': 46, 'name': 'detergent'},
{'id': 47, 'name': 'iron'},
{'id': 48, 'name': 'ironing board'},
{'id': 49, 'name': 'laundry basket'},
{'id': 50, 'name': 'clothes hanger'},
{'id': 51, 'name': 'coat rack'},
{'id': 52, 'name': 'shoe rack'},
{'id': 53, 'name': 'umbrella'},
{'id': 54, 'name': 'fire extinguisher'},
{'id': 55, 'name': 'first aid kit'},
{'id': 56, 'name': 'thermometer'},
{'id': 57, 'name': 'scale'},
{'id': 58, 'name': 'fan'},
{'id': 59, 'name': 'heater'},
{'id': 60, 'name': 'air conditioner'},
{'id': 61, 'name': 'humidifier'},
{'id': 62, 'name': 'dehumidifier'},
{'id': 63, 'name': 'light switch'},
{'id': 64, 'name': 'electrical outlet'},
{'id': 65, 'name': 'extension cord'},
{'id': 66, 'name': 'remote control'},
{'id': 67, 'name': 'game console'},
{'id': 68, 'name': 'router'},
{'id': 69, 'name': 'modem'},
{'id': 70, 'name': 'computer'},
{'id': 71, 'name': 'laptop'},
{'id': 72, 'name': 'printer'},
{'id': 73, 'name': 'scanner'},
{'id': 74, 'name': 'fax machine'},
{'id': 75, 'name': 'telephone'},
{'id': 76, 'name': 'smartphone'},
{'id': 77, 'name': 'tablet'},
{'id': 78, 'name': 'keyboard'},
{'id': 79, 'name': 'mouse'},
{'id': 80, 'name': 'monitor'},
{'id': 81, 'name': 'notebook'},
{'id': 82, 'name': 'pen'},
{'id': 83, 'name': 'pencil'},
{'id': 84, 'name': 'eraser'},
{'id': 85, 'name': 'stapler'},
{'id': 86, 'name': 'scissors'},
{'id': 87, 'name': 'tape dispenser'},
{'id': 88, 'name': 'paper clip'},
{'id': 89, 'name': 'envelope'},
{'id': 90, 'name': 'letter opener'},
{'id': 91, 'name': 'cabinet'},
{'id': 92, 'name': 'whiteboard'},
{'id': 93, 'name': 'calendar'},
{'id': 94, 'name': 'photo frame'},
{'id': 95, 'name': 'vase'},
{'id': 96, 'name': 'candle'},
{'id': 97, 'name': 'incense'},
{'id': 98, 'name': 'book'},
{'id': 99, 'name': 'magazine'},
{'id': 100, 'name': 'newspaper'},
{'id': 101, 'name': 'album'},
{'id': 102, 'name': 'record player'},
{'id': 103, 'name': 'cd player'},
{'id': 104, 'name': 'dvd player'},
{'id': 105, 'name': 'blu ray player'},
{'id': 106, 'name': 'speaker'},
{'id': 107, 'name': 'headphones'},
{'id': 108, 'name': 'microphone'},
{'id': 109, 'name': 'camera'},
{'id': 110, 'name': 'camcorder'},
{'id': 111, 'name': 'tripod'},
{'id': 112, 'name': 'flashlight'},
{'id': 113, 'name': 'batteries'},
{'id': 114, 'name': 'charger'},
{'id': 115, 'name': 'cable'},
{'id': 116, 'name': 'usb drive'},
{'id': 117, 'name': 'hard drive'},
{'id': 118, 'name': 'router'},
{'id': 119, 'name': 'switch'},
{'id': 120, 'name': 'firewall'},
{'id': 121, 'name': 'server'},
{'id': 122, 'name': 'keyboard tray'},
{'id': 123, 'name': 'mouse pad'},
{'id': 124, 'name': 'speaker stand'},
{'id': 125, 'name': 'monitor stand'},
{'id': 126, 'name': 'file folder'},
{'id': 127, 'name': 'binder'},
{'id': 128, 'name': 'clipboard'},
{'id': 129, 'name': 'calculator'},
{'id': 130, 'name': 'label maker'},
{'id': 131, 'name': 'hole punch'},
{'id': 132, 'name': 'paper shredder'},
{'id': 133, 'name': 'post it note'},
{'id': 134, 'name': 'thumbtack'},
{'id': 135, 'name': 'magnet'},
{'id': 136, 'name': 'ruler'},
{'id': 137, 'name': 'protractor'},
{'id': 138, 'name': 'compass'},
{'id': 139, 'name': 'glue'},
{'id': 140, 'name': 'white out'},
{'id': 141, 'name': 'marker'},
{'id': 142, 'name': 'highlighter'},
{'id': 143, 'name': 'crayon'},
{'id': 144, 'name': 'paint'},
{'id': 145, 'name': 'paintbrush'},
{'id': 146, 'name': 'easel'},
{'id': 147, 'name': 'canvas'},
{'id': 148, 'name': 'palette'},
{'id': 149, 'name': 'sculpting tools'},
{'id': 150, 'name': 'clay'},
{'id': 151, 'name': 'sewing machine'},
{'id': 152, 'name': 'thread'},
{'id': 153, 'name': 'needle'},
{'id': 154, 'name': 'scissors'},
{'id': 155, 'name': 'fabric'},
{'id': 156, 'name': 'measuring tape'},
{'id': 157, 'name': 'pin cushion'},
{'id': 158, 'name': 'thimble'},
{'id': 159, 'name': 'seam ripper'},
{'id': 160, 'name': 'iron'},
{'id': 161, 'name': 'pattern'},
{'id': 162, 'name': 'ribbon'},
{'id': 163, 'name': 'button'},
{'id': 164, 'name': 'zipper'},
{'id': 165, 'name': 'hook'},
{'id': 166, 'name': 'stairs'},
{'id': 167, 'name': 'snap'},
{'id': 168, 'name': 'velcro'},
{'id': 169, 'name': 'elastic'},
{'id': 170, 'name': 'lace'},
{'id': 171, 'name': 'trim'},
{'id': 172, 'name': 'bead'},
{'id': 173, 'name': 'sequin'},
{'id': 174, 'name': 'glue gun'},
{'id': 175, 'name': 'glue stick'},
{'id': 176, 'name': 'craft knife'},
{'id': 177, 'name': 'cutting mat'},
{'id': 178, 'name': 'ruler'},
{'id': 179, 'name': 'scalpel'},
{'id': 180, 'name': 'tweezers'},
{'id': 181, 'name': 'pliers'},
{'id': 182, 'name': 'hammer'},
{'id': 183, 'name': 'screwdriver'},
{'id': 184, 'name': 'wrench'},
{'id': 185, 'name': 'drill'},
{'id': 186, 'name': 'saw'},
{'id': 187, 'name': 'chisel'},
{'id': 188, 'name': 'level'},
{'id': 189, 'name': 'tape measure'},
{'id': 190, 'name': 'toolbox'},
{'id': 191, 'name': 'nail'},
{'id': 192, 'name': 'screw'},
{'id': 193, 'name': 'bolt'},
{'id': 194, 'name': 'nut'},
{'id': 195, 'name': 'washer'},
{'id': 196, 'name': 'sandpaper'},
{'id': 197, 'name': 'wood glue'},
{'id': 198, 'name': 'clamp'},
{'id': 199, 'name': 'vise'},
{'id': 200, 'name': 'workbench'},
{'id': 201, 'name': 'accordion'},
{'id': 202, 'name': 'aeroplane'},
{'id': 203, 'name': 'antenna'},
{'id': 204, 'name': 'artillery'},
{'id': 205, 'name': 'ashtray'},
{'id': 206, 'name': 'atrium'},
{'id': 207, 'name': 'baby carriage'},
{'id': 208, 'name': 'bag'},
{'id': 209, 'name': 'ball'},
{'id': 210, 'name': 'balloon'},
{'id': 211, 'name': 'bamboo weaving'},
{'id': 212, 'name': 'barrel'},
{'id': 213, 'name': 'baseball bat'},
{'id': 214, 'name': 'basket'},
{'id': 215, 'name': 'basketball backboard'},
{'id': 216, 'name': 'bedclothes'},
{'id': 217, 'name': 'beer'},
{'id': 218, 'name': 'bell'},
{'id': 219, 'name': 'bench'},
{'id': 220, 'name': 'bicycle'},
{'id': 221, 'name': 'binoculars'},
{'id': 222, 'name': 'bird'},
{'id': 223, 'name': 'bird cage'},
{'id': 224, 'name': 'bird feeder'},
{'id': 225, 'name': 'bird nest'},
{'id': 226, 'name': 'blackboard'},
{'id': 227, 'name': 'board'},
{'id': 228, 'name': 'boat'},
{'id': 229, 'name': 'bone'},
{'id': 230, 'name': 'bottle'},
{'id': 231, 'name': 'bottle opener'},
{'id': 232, 'name': 'bowl'},
{'id': 233, 'name': 'box'},
{'id': 234, 'name': 'bracelet'},
{'id': 235, 'name': 'brick'},
{'id': 236, 'name': 'bridge'},
{'id': 237, 'name': 'brush'},
{'id': 238, 'name': 'building'},
{'id': 239, 'name': 'bus'},
{'id': 240, 'name': 'cabinet door'},
{'id': 241, 'name': 'cage'},
{'id': 242, 'name': 'cake'},
{'id': 243, 'name': 'camel'},
{'id': 244, 'name': 'camera lens'},
{'id': 245, 'name': 'can'},
{'id': 246, 'name': 'candle holder'},
{'id': 247, 'name': 'cap'},
{'id': 248, 'name': 'car'},
{'id': 249, 'name': 'card'},
{'id': 250, 'name': 'cart'},
{'id': 251, 'name': 'case'},
{'id': 252, 'name': 'casette recorder'},
{'id': 253, 'name': 'cash register'},
{'id': 254, 'name': 'cat'},
{'id': 255, 'name': 'cd'},
{'id': 256, 'name': 'ceiling'},
{'id': 257, 'name': 'cell phone'},
{'id': 258, 'name': 'cello'},
{'id': 259, 'name': 'chain'},
{'id': 260, 'name': 'chessboard'},
{'id': 261, 'name': 'chicken'},
{'id': 262, 'name': 'chopstick'},
{'id': 263, 'name': 'clip'},
{'id': 264, 'name': 'clippers'},
{'id': 265, 'name': 'closet'},
{'id': 266, 'name': 'cloth'},
{'id': 267, 'name': 'clothes tree'},
{'id': 268, 'name': 'coffee'},
{'id': 269, 'name': 'comb'},
{'id': 270, 'name': 'concrete'},
{'id': 271, 'name': 'cone'},
{'id': 272, 'name': 'container'},
{'id': 273, 'name': 'control booth'},
{'id': 274, 'name': 'controller'},
{'id': 275, 'name': 'cooker'},
{'id': 276, 'name': 'copying machine'},
{'id': 277, 'name': 'coral'},
{'id': 278, 'name': 'cork'},
{'id': 279, 'name': 'corkscrew'},
{'id': 280, 'name': 'counter'},
{'id': 281, 'name': 'court'},
{'id': 282, 'name': 'cow'},
{'id': 283, 'name': 'crabstick'},
{'id': 284, 'name': 'crane'},
{'id': 285, 'name': 'crate'},
{'id': 286, 'name': 'cross'},
{'id': 287, 'name': 'crutch'},
{'id': 288, 'name': 'cup'},
{'id': 289, 'name': 'curtain'},
{'id': 290, 'name': 'cushion'},
{'id': 291, 'name': 'cutting board'},
{'id': 292, 'name': 'dais'},
{'id': 293, 'name': 'disc'},
{'id': 294, 'name': 'disc case'},
{'id': 295, 'name': 'dock'},
{'id': 296, 'name': 'dog'},
{'id': 297, 'name': 'dolphin'},
{'id': 298, 'name': 'door'},
{'id': 299, 'name': 'drainer'},
{'id': 300, 'name': 'dray'},
{'id': 301, 'name': 'drink dispenser'},
{'id': 302, 'name': 'drinking machine'},
{'id': 303, 'name': 'drop'},
{'id': 304, 'name': 'drug'},
{'id': 305, 'name': 'drum'},
{'id': 306, 'name': 'drum kit'},
{'id': 307, 'name': 'duck'},
{'id': 308, 'name': 'dumbbell'},
{'id': 309, 'name': 'earphone'},
{'id': 310, 'name': 'earrings'},
{'id': 311, 'name': 'egg'},
{'id': 312, 'name': 'electric fan'},
{'id': 313, 'name': 'electric iron'},
{'id': 314, 'name': 'electric pot'},
{'id': 315, 'name': 'electric saw'},
{'id': 316, 'name': 'electronic keyboard'},
{'id': 317, 'name': 'engine'},
{'id': 318, 'name': 'equipment'},
{'id': 319, 'name': 'escalator'},
{'id': 320, 'name': 'exhibition booth'},
{'id': 321, 'name': 'extinguisher'},
{'id': 322, 'name': 'eyeglass'},
{'id': 323, 'name': 'faucet'},
{'id': 324, 'name': 'fence'},
{'id': 325, 'name': 'ferris wheel'},
{'id': 326, 'name': 'fire hydrant'},
{'id': 327, 'name': 'fire place'},
{'id': 328, 'name': 'fish'},
{'id': 329, 'name': 'fish tank'},
{'id': 330, 'name': 'fishbowl'},
{'id': 331, 'name': 'fishing net'},
{'id': 332, 'name': 'fishing pole'},
{'id': 333, 'name': 'flag'},
{'id': 334, 'name': 'flagstaff'},
{'id': 335, 'name': 'flame'},
{'id': 336, 'name': 'floor'},
{'id': 337, 'name': 'flower'},
{'id': 338, 'name': 'fly'},
{'id': 339, 'name': 'foam'},
{'id': 340, 'name': 'food'},
{'id': 341, 'name': 'footbridge'},
{'id': 342, 'name': 'forceps'},
{'id': 343, 'name': 'fork'},
{'id': 344, 'name': 'forklift'},
{'id': 345, 'name': 'fountain'},
{'id': 346, 'name': 'fox'},
{'id': 347, 'name': 'frame'},
{'id': 348, 'name': 'fridge'},
{'id': 349, 'name': 'frog'},
{'id': 350, 'name': 'fruit'},
{'id': 351, 'name': 'funnel'},
{'id': 352, 'name': 'furnace'},
{'id': 353, 'name': 'game controller'},
{'id': 354, 'name': 'game machine'},
{'id': 355, 'name': 'gas cylinder'},
{'id': 356, 'name': 'gas hood'},
{'id': 357, 'name': 'gas stove'},
{'id': 358, 'name': 'gift box'},
{'id': 359, 'name': 'glass'},
{'id': 360, 'name': 'glass marble'},
{'id': 361, 'name': 'globe'},
{'id': 362, 'name': 'glove'},
{'id': 363, 'name': 'goal'},
{'id': 364, 'name': 'grandstand'},
{'id': 365, 'name': 'grass'},
{'id': 366, 'name': 'gravestone'},
{'id': 367, 'name': 'ground'},
{'id': 368, 'name': 'guardrail'},
{'id': 369, 'name': 'guitar'},
{'id': 370, 'name': 'gun'},
{'id': 371, 'name': 'hand cart'},
{'id': 372, 'name': 'handle'},
{'id': 373, 'name': 'handrail'},
{'id': 374, 'name': 'hanger'},
{'id': 375, 'name': 'hard disk drive'},
{'id': 376, 'name': 'hat'},
{'id': 377, 'name': 'hay'},
{'id': 378, 'name': 'headphone'},
{'id': 379, 'name': 'helicopter'},
{'id': 380, 'name': 'helmet'},
{'id': 381, 'name': 'holder'},
{'id': 382, 'name': 'horse'},
{'id': 383, 'name': 'horse-drawn carriage'},
{'id': 384, 'name': 'hot-air balloon'},
{'id': 385, 'name': 'hydrovalve'},
{'id': 386, 'name': 'ice'},
{'id': 387, 'name': 'inflator pump'},
{'id': 388, 'name': 'ipod'},
{'id': 389, 'name': 'jar'},
{'id': 390, 'name': 'kart'},
{'id': 391, 'name': 'key'},
{'id': 392, 'name': 'kitchen range'},
{'id': 393, 'name': 'kite'},
{'id': 394, 'name': 'knife'},
{'id': 395, 'name': 'knife block'},
{'id': 396, 'name': 'ladder'},
{'id': 397, 'name': 'ladder truck'},
{'id': 398, 'name': 'ladle'},
{'id': 399, 'name': 'leaves'},
{'id': 400, 'name': 'lid'},
{'id': 401, 'name': 'life buoy'},
{'id': 402, 'name': 'light'},
{'id': 403, 'name': 'light bulb'},
{'id': 404, 'name': 'lighter'},
{'id': 405, 'name': 'line'},
{'id': 406, 'name': 'lion'},
{'id': 407, 'name': 'lobster'},
{'id': 408, 'name': 'lock'},
{'id': 409, 'name': 'machine'},
{'id': 410, 'name': 'mailbox'},
{'id': 411, 'name': 'mannequin'},
{'id': 412, 'name': 'map'},
{'id': 413, 'name': 'mask'},
{'id': 414, 'name': 'mat'},
{'id': 415, 'name': 'match book'},
{'id': 416, 'name': 'mattress'},
{'id': 417, 'name': 'menu'},
{'id': 418, 'name': 'metal'},
{'id': 419, 'name': 'meter box'},
{'id': 420, 'name': 'missile'},
{'id': 421, 'name': 'model'},
{'id': 422, 'name': 'money'},
{'id': 423, 'name': 'monkey'},
{'id': 424, 'name': 'motorbike'},
{'id': 425, 'name': 'mountain'},
{'id': 426, 'name': 'musical instrument'},
{'id': 427, 'name': 'napkin'},
{'id': 428, 'name': 'net'},
{'id': 429, 'name': 'oar'},
{'id': 430, 'name': 'ornament'},
{'id': 431, 'name': 'outlet'},
{'id': 432, 'name': 'oxygen bottle'},
{'id': 433, 'name': 'pack'},
{'id': 434, 'name': 'pan'},
{'id': 435, 'name': 'paper'},
{'id': 436, 'name': 'paper box'},
{'id': 437, 'name': 'paper cutter'},
{'id': 438, 'name': 'parachute'},
{'id': 439, 'name': 'parasol'},
{'id': 440, 'name': 'parterre'},
{'id': 441, 'name': 'patio'},
{'id': 442, 'name': 'pelage'},
{'id': 443, 'name': 'pen container'},
{'id': 444, 'name': 'person'},
{'id': 445, 'name': 'photo'},
{'id': 446, 'name': 'piano'},
{'id': 447, 'name': 'picture'},
{'id': 448, 'name': 'pig'},
{'id': 449, 'name': 'pillar'},
{'id': 450, 'name': 'pillow'},
{'id': 451, 'name': 'pipe'},
{'id': 452, 'name': 'pitcher'},
{'id': 453, 'name': 'plant'},
{'id': 454, 'name': 'plastic'},
{'id': 455, 'name': 'plate'},
{'id': 456, 'name': 'platform'},
{'id': 457, 'name': 'player'},
{'id': 458, 'name': 'playground'},
{'id': 459, 'name': 'plume'},
{'id': 460, 'name': 'poker'},
{'id': 461, 'name': 'poker chip'},
{'id': 462, 'name': 'pole'},
{'id': 463, 'name': 'pool table'},
{'id': 464, 'name': 'postcard'},
{'id': 465, 'name': 'poster'},
{'id': 466, 'name': 'pot'},
{'id': 467, 'name': 'pottedplant'},
{'id': 468, 'name': 'projector'},
{'id': 469, 'name': 'pumpkin'},
{'id': 470, 'name': 'rabbit'},
{'id': 471, 'name': 'racket'},
{'id': 472, 'name': 'radiator'},
{'id': 473, 'name': 'radio'},
{'id': 474, 'name': 'rail'},
{'id': 475, 'name': 'rake'},
{'id': 476, 'name': 'ramp'},
{'id': 477, 'name': 'range hood'},
{'id': 478, 'name': 'receiver'},
{'id': 479, 'name': 'recorder'},
{'id': 480, 'name': 'recreational machines'},
{'id': 481, 'name': 'road'},
{'id': 482, 'name': 'robot'},
{'id': 483, 'name': 'rock'},
{'id': 484, 'name': 'rocket'},
{'id': 485, 'name': 'rocking horse'},
{'id': 486, 'name': 'rope'},
{'id': 487, 'name': 'rug'},
{'id': 488, 'name': 'runway'},
{'id': 489, 'name': 'saddle'},
{'id': 490, 'name': 'sand'},
{'id': 491, 'name': 'scoop'},
{'id': 492, 'name': 'screen'},
{'id': 493, 'name': 'sculpture'},
{'id': 494, 'name': 'scythe'},
{'id': 495, 'name': 'sewer'},
{'id': 496, 'name': 'shed'},
{'id': 497, 'name': 'sheep'},
{'id': 498, 'name': 'shell'},
{'id': 499, 'name': 'shelves'},
{'id': 500, 'name': 'shoe'},
{'id': 501, 'name': 'shopping cart'},
{'id': 502, 'name': 'shovel'},
{'id': 503, 'name': 'sidecar'},
{'id': 504, 'name': 'sidewalk'},
{'id': 505, 'name': 'sign'},
{'id': 506, 'name': 'signal light'},
{'id': 507, 'name': 'skateboard'},
{'id': 508, 'name': 'ski'},
{'id': 509, 'name': 'sky'},
{'id': 510, 'name': 'sled'},
{'id': 511, 'name': 'slippers'},
{'id': 512, 'name': 'smoke'},
{'id': 513, 'name': 'snail'},
{'id': 514, 'name': 'snake'},
{'id': 515, 'name': 'snow'},
{'id': 516, 'name': 'snowmobiles'},
{'id': 517, 'name': 'spanner'},
{'id': 518, 'name': 'spatula'},
{'id': 519, 'name': 'speed bump'},
{'id': 520, 'name': 'spice container'},
{'id': 521, 'name': 'spoon'},
{'id': 522, 'name': 'sprayer'},
{'id': 523, 'name': 'squirrel'},
{'id': 524, 'name': 'stage'},
{'id': 525, 'name': 'stair'},
{'id': 526, 'name': 'stick'},
{'id': 527, 'name': 'sticky note'},
{'id': 528, 'name': 'stone'},
{'id': 529, 'name': 'stool'},
{'id': 530, 'name': 'straw'},
{'id': 531, 'name': 'stretcher'},
{'id': 532, 'name': 'sun'},
{'id': 533, 'name': 'sunglass'},
{'id': 534, 'name': 'sunshade'},
{'id': 535, 'name': 'surveillance camera'},
{'id': 536, 'name': 'swan'},
{'id': 537, 'name': 'sweeper'},
{'id': 538, 'name': 'swim ring'},
{'id': 539, 'name': 'swimming pool'},
{'id': 540, 'name': 'swing'},
{'id': 541, 'name': 'tableware'},
{'id': 542, 'name': 'tank'},
{'id': 543, 'name': 'tap'},
{'id': 544, 'name': 'tape'},
{'id': 545, 'name': 'tarp'},
{'id': 546, 'name': 'telephone booth'},
{'id': 547, 'name': 'tent'},
{'id': 548, 'name': 'tire'},
{'id': 549, 'name': 'tong'},
{'id': 550, 'name': 'tool'},
{'id': 551, 'name': 'toy'},
{'id': 552, 'name': 'toy car'},
{'id': 553, 'name': 'track'},
{'id': 554, 'name': 'train'},
{'id': 555, 'name': 'trampoline'},
{'id': 556, 'name': 'trash bin'},
{'id': 557, 'name': 'tray'},
{'id': 558, 'name': 'tree'},
{'id': 559, 'name': 'tricycle'},
{'id': 560, 'name': 'trophy'},
{'id': 561, 'name': 'truck'},
{'id': 562, 'name': 'tube'},
{'id': 563, 'name': 'turtle'},
{'id': 564, 'name': 'tvmonitor'},
{'id': 565, 'name': 'typewriter'},
{'id': 566, 'name': 'unknown'},
{'id': 567, 'name': 'vending machine'},
{'id': 568, 'name': 'video camera'},
{'id': 569, 'name': 'video game console'},
{'id': 570, 'name': 'video player'},
{'id': 571, 'name': 'video tape'},
{'id': 572, 'name': 'violin'},
{'id': 573, 'name': 'wakeboard'},
{'id': 574, 'name': 'wall'},
{'id': 575, 'name': 'wallet'},
{'id': 576, 'name': 'wardrobe'},
{'id': 577, 'name': 'watch'},
{'id': 578, 'name': 'water'},
{'id': 579, 'name': 'water dispenser'},
{'id': 580, 'name': 'water pipe'},
{'id': 581, 'name': 'water skate board'},
{'id': 582, 'name': 'watermelon'},
{'id': 583, 'name': 'whale'},
{'id': 584, 'name': 'wharf'},
{'id': 585, 'name': 'wheel'},
{'id': 586, 'name': 'wheelchair'},
{'id': 587, 'name': 'window'},
{'id': 588, 'name': 'window blinds'},
{'id': 589, 'name': 'wineglass'},
{'id': 590, 'name': 'wire'},
{'id': 591, 'name': 'wood'},
{'id': 592, 'name': 'wool'},
{'id': 593, 'name': 'shirt'},
{'id': 594, 'name': 'pants'},
{'id': 595, 'name': 'shorts'},
{'id': 596, 'name': 'T-shirt'},
{'id': 597, 'name': 'skirt'},
{'id': 598, 'name': 'sweater'},
{'id': 599, 'name': 'coat'},
{'id': 600, 'name': 'jeans'},
{'id': 601, 'name': 'hoodie'},
{'id': 602, 'name': 'dress'},
{'id': 603, 'name': 'jacket'},
{'id': 604, 'name': 'suit'},
{'id': 605, 'name': 'tie'},
{'id': 606, 'name': 'scarf'},
{'id': 607, 'name': 'gloves'},
{'id': 608, 'name': 'hat'},
{'id': 609, 'name': 'cap'},
{'id': 610, 'name': 'sunglasses'},
{'id': 611, 'name': 'watch'},
{'id': 612, 'name': 'bracelet'},
{'id': 613, 'name': 'necklace'},
{'id': 614, 'name': 'earrings'},
{'id': 615, 'name': 'ring'},
{'id': 616, 'name': 'bag'},
{'id': 617, 'name': 'backpack'},
]
